name: Integration Tests
on:
  merge_group:
    types: [checks_requested]
  pull_request:

jobs:
  test-basic-flow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/bake-action@v3
        with:
          files: docker-compose.yml
          push: false
      - name: Start docker compose in the background
        run: docker compose up -d
      - name: Test that client can ping resource
        run: docker compose exec -it client ping 172.20.0.100 -c 4
